#!/usr/bin/env bash

source "./test/automated/integration/init"

output="$(LOG_DEVICE=stdout LOG_TAGS=-someTag log_without_timestamp)"

expected=$(cat <<'END_HEREDOC'
[] TRACE trace message (SomeKey: some value, SomeOtherKey: 123)
[] FATAL fatal message
END_HEREDOC
)

assert "$output" "$expected"
