#!/usr/bin/env bash

source "./test/automated/integration/init"

output="$(LOG_DEVICE=stdout LOG_TAGS=+someTag log_without_timestamp)"

expected=$(cat <<'END_HEREDOC'
[] DEBUG {
  "SomeBool": true,
  "SomeKey": "some value",
  "SomeOtherKey": 123
}
{"timestamp":"","level":"warn","message":"warn message","tags":["someTag","warn"],"data":{"SomeBool":true,"SomeKey":"some value","SomeOtherKey":123}}
END_HEREDOC
)

assert "$output" "$expected"
