#!/usr/bin/env bash

source "./test/automated/integration/init"

output="$(LOG_DEVICE=stdout LOG_LEVEL=fatal log_without_timestamp)"

expected=$(cat <<'END_HEREDOC'
[] FATAL fatal message
END_HEREDOC
)

assert "$output" "$expected"
